# Generated by Django 3.0.3 on 2020-08-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websure_faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.FilePathField(allow_folders=True, blank=True),
        ),
    ]
