# Generated by Django 3.0.3 on 2020-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websure_faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
