# Generated by Django 3.0.3 on 2020-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websure_faq', '0003_auto_20200820_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.FilePathField(allow_folders=True, blank=True, default=None, path=None),
        ),
    ]
