# Generated by Django 3.0.3 on 2020-08-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websure_faq', '0004_auto_20200820_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
    ]
